# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main

pool:
  name: 'Comp367Lab4-SelfHosted-CIAgent-Win' # Ensure this is your self-hosted agent pool name

variables:
  solution: '**/*.sln' # Searches for solution files
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: '8.x' # Adjust this to match your ASP.Net project's required SDK version
      
  - script: dotnet restore
    displayName: 'Restore Dependencies'

  - script: dotnet build --configuration Release
    displayName: 'Build Solution'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet Tool'

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)' # Restores NuGet packages for the solution
    displayName: 'Restore NuGet Packages'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)/WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
    displayName: 'Build ASP.Net Solution'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
    displayName: 'Run Unit Tests'